#!/usr/bin/env bash

P="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/run/current-system/sw/bin"
PL="/usr/sbin:/usr/bin:/sbin:/bin:/run/current-system/sw/bin"

container_supported_filesystems=(
  "ext2"
  "ext3"
  "ext4"
  "ext4dev"
  "btrfs"
  "xfs"
  "vfat"
  "nfs"
  "nfs3"
  "nfs4"
  "cifs"
  "smb"
  "smb3"
  "bind"
)

# Parse arguments to detect filesystem type without consuming them
for arg in "$@"; do
  if [[ "$prev_arg" == "-t" ]]; then
    if [[ "x${USE_HOST_MOUNT_TOOLS}" == "x" ]]; then
      [[ "${arg,,}" == "zfs" ]] && USE_HOST_MOUNT_TOOLS=1
      [[ "${arg,,}" == "lustre" ]] && USE_HOST_MOUNT_TOOLS=1
      [[ "${arg,,}" == "onedata" ]] && USE_HOST_MOUNT_TOOLS=1
      #(printf '%s\0' "${container_supported_filesystems[@]}" | grep -Fqxz -- "${arg}") || USE_HOST_MOUNT_TOOLS=1
    fi
    break
  fi
  prev_arg="$arg"
done

if [[ ${USE_HOST_MOUNT_TOOLS} -eq 1 ]]; then
  for p in $(echo $P | cut -d ":" -f 1- --output-delimiter=" "); do
    if [[ -f "/host${p}/mount" ]]; then
      chroot /host "${p}/mount" "$@"
      exit $?
    fi
  done
  chroot /host /usr/bin/env -i PATH="${P}" mount "$@"
  exit $?
else
  /usr/bin/env -i PATH="${PL}" mount "$@"
  exit $?
fi
