#!/bin/bash

if [[ ${USE_HOST_MOUNT_TOOLS} -eq 1 ]];then
  chroot /host /usr/bin/env -i PATH="/sbin:/bin:/usr/bin:/usr/sbin" umount "${@:1}"
else
  /usr/bin/env -i PATH="/sbin:/bin:/usr/bin:/usr/sbin" umount "${@:1}"
fi
