driver: local-xfs-hostpath
instance_id:
local-xfs-hostpath:
  shareBasePath:      "/tmp/local-xfs-hostpath/${CI_BUILD_KEY}/controller"
  controllerBasePath: "/tmp/local-xfs-hostpath/${CI_BUILD_KEY}/controller"
  dirPermissionsMode: "0777"
  dirPermissionsUser: root
  dirPermissionsGroup: root
