driver: xfs-local-hostpath
instance_id:
xfs-local-hostpath:
  shareBasePath:      "/tmp/xfs-local-hostpath/${CI_BUILD_KEY}/controller"
  controllerBasePath: "/tmp/xfs-local-hostpath/${CI_BUILD_KEY}/controller"
  dirPermissionsMode: "0777"
  dirPermissionsUser: root
  dirPermissionsGroup: root
