driver: freenas-api-smb

httpConnection:
  protocol: http
  host: ${TRUENAS_HOST}
  port: 80
  #apiKey:
  username: ${TRUENAS_USERNAME}
  password: ${TRUENAS_PASSWORD}

zfs:
  datasetParentName: tank/ci/${CI_BUILD_KEY}/v
  detachedSnapshotsDatasetParentName: tank/ci/${CI_BUILD_KEY}/s

  datasetEnableQuotas: true
  datasetEnableReservation: false
  #datasetPermissionsMode: "0770"
  #datasetPermissionsUser: 1001
  #datasetPermissionsGroup: 1001

smb:
  shareHost: ${TRUENAS_HOST}
  #nameTemplate: ""
  namePrefix: "csi-ci-${CI_BUILD_KEY}-"
  nameSuffix: ""
  shareAuxiliaryConfigurationTemplate: |
    #guest ok = yes
    #guest only = yes
  shareHome: false
  shareAllowedHosts: []
  shareDeniedHosts: []
  #shareDefaultPermissions: true
  shareGuestOk: false
  #shareGuestOnly: true
  #shareShowHiddenFiles: true
  shareRecycleBin: false
  shareBrowsable: false
  shareAccessBasedEnumeration: true
  shareTimeMachine: false
  #shareStorageTask:

node:
  mount:
    mount_flags: "username=smbroot,password=smbroot"

_private:
  csi:
    volume:
      idHash:
        strategy: crc16
